name: Node.js CI

on:
  push:
    branches: [ digitalocean-deploy1 ]
  pull_request:
    branches: [ digitalocean-deploy1 ]

jobs:
  build: 
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node }}
    - run: |
        git config --global url."git@github.com:".insteadOf git://github.com/ && npm install
        npm i
        cd client
        npm i
        npm run build