name: Node.js CI

on:
  push:
    branches: [ digitalocean-deploy1 ]
  pull_request:
    branches: [ digitalocean-deploy1 ]

jobs:
  build: 
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: |
        npm i
        cd client
        npm i
        npm run build